apiVersion: v1
kind: Service
metadata:
  labels:
    app: endpoints
  name: endpoints
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: endpoints
